=begin
#Role Based Access Control

#The API for Role Based Access Control.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.2

=end

require 'spec_helper'
require 'json'

# Unit tests for RBACApiClient::AccessApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AccessApi' do
  before do
    # run before each test
    @api_instance = RBACApiClient::AccessApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AccessApi' do
    it 'should create an instance of AccessApi' do
      expect(@api_instance).to be_instance_of(RBACApiClient::AccessApi)
    end
  end

  # unit tests for get_principal_access
  # Get the permitted access for a principal in the tenant (defaults to principal from the identity header)
  # Access responses are sorted in ascending order by an ID internal to the database
  # @param application The application name(s) to obtain access for the principal. This is an exact match. When no application is supplied, all permissions for the principal are returned. You may also use a comma-separated list to match on multiple applications.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :username Unique username of the principal to obtain access for (only available for admins, and if supplied, takes precedence over the identity header).
  # @option opts [Integer] :limit Parameter for selecting the amount of data returned.
  # @option opts [Integer] :offset Parameter for selecting the offset of data.
  # @return [AccessPagination]
  describe 'get_principal_access test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
