=begin
#Role Based Access Control

#The API for Role Based Access Control.

OpenAPI spec version: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.3.4

=end

require 'spec_helper'
require 'json'

# Unit tests for RBACApiClient::PrincipalApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PrincipalApi' do
  before do
    # run before each test
    @instance = RBACApiClient::PrincipalApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PrincipalApi' do
    it 'should create an instance of PrincipalApi' do
      expect(@instance).to be_instance_of(RBACApiClient::PrincipalApi)
    end
  end

  # unit tests for list_principals
  # List the principals for a tenant
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit Parameter for selecting the amount of data returned.
  # @option opts [Integer] :offset Parameter for selecting the offset of data.
  # @option opts [String] :usernames Usernames of principals to get
  # @return [PrincipalPagination]
  describe 'list_principals test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
