=begin
#Role Based Access Control

#The API for Role Based Access Control.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.1.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for RBACApiClient::PrincipalApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PrincipalApi' do
  before do
    # run before each test
    @api_instance = RBACApiClient::PrincipalApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PrincipalApi' do
    it 'should create an instance of PrincipalApi' do
      expect(@api_instance).to be_instance_of(RBACApiClient::PrincipalApi)
    end
  end

  # unit tests for list_principals
  # List the principals for a tenant
  # By default, responses are sorted in ascending order by username
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit Parameter for selecting the amount of data returned.
  # @option opts [Integer] :offset Parameter for selecting the offset of data.
  # @option opts [String] :match_criteria Parameter for specifying the matching criteria for an object&#39;s name and/or email. Currently, match_criteria of partial searches for a username/email using \&quot;starts with\&quot; pattern.
  # @option opts [String] :usernames Comma separated usernames of principals to get. If match_criteria is specified, only the first username will be picked up for search.
  # @option opts [String] :sort_order The sort order of the query, either ascending or descending. Defaults to ascending.
  # @option opts [String] :email E-mail address of principal to search for. Could be combined with match_criteria for searching.
  # @option opts [String] :status Set the status of users to get back.
  # @option opts [String] :admin_only Get only admin users within an account. Setting this would ignore the parameters: usernames, email
  # @option opts [String] :order_by Parameter for ordering principals by value. For inverse ordering, supply &#39;-&#39; before the param value, such as: ?order_by&#x3D;-username
  # @option opts [Boolean] :username_only Parameter for optionally returning only usernames for principals, bypassing a call to IT.
  # @return [PrincipalPagination]
  describe 'list_principals test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
