=begin
#Role Based Access Control

#The API for Role Based Access Control.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.2

=end

require 'spec_helper'
require 'json'

# Unit tests for RBACApiClient::RoleApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'RoleApi' do
  before do
    # run before each test
    @api_instance = RBACApiClient::RoleApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RoleApi' do
    it 'should create an instance of RoleApi' do
      expect(@api_instance).to be_instance_of(RBACApiClient::RoleApi)
    end
  end

  # unit tests for create_roles
  # Create a roles for a tenant
  # @param role_in Role to create
  # @param [Hash] opts the optional parameters
  # @return [RoleWithAccess]
  describe 'create_roles test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_role
  # Delete a role in the tenant
  # @param uuid ID of role to delete
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_role test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_role
  # Get a role in the tenant
  # @param uuid ID of role to get
  # @param [Hash] opts the optional parameters
  # @return [RoleWithAccess]
  describe 'get_role test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_role_access
  # Get access for a role in the tenant
  # @param uuid ID of the role
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit Parameter for selecting the amount of data returned.
  # @option opts [Integer] :offset Parameter for selecting the offset of data.
  # @return [AccessPagination]
  describe 'get_role_access test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_roles
  # List the roles for a tenant
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit Parameter for selecting the amount of data returned.
  # @option opts [Integer] :offset Parameter for selecting the offset of data.
  # @option opts [String] :name Parameter for filtering resource by name using string contains search.
  # @option opts [String] :scope Parameter for filtering resource by scope.
  # @option opts [String] :order_by Parameter for ordering resource by value. For inverse ordering, supply &#39;-&#39; before the param value, such as: ?order_by&#x3D;-name
  # @option opts [Array<String>] :add_fields Parameter for add list of fields to display for roles.
  # @option opts [String] :username Unique username of the principal to obtain roles for (only available for admins, and if supplied, takes precedence over the identity header).
  # @return [RolePaginationDynamic]
  describe 'list_roles test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_role
  # Update a Role in the tenant
  # @param uuid ID of role to update
  # @param role_with_access Update to a Role
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'update_role test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
