=begin
#Role Based Access Control

#The API for Role Based Access Control.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.1.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for RBACApiClient::CrossAccountRequestWithRolesRolesInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe RBACApiClient::CrossAccountRequestWithRolesRolesInner do
  let(:instance) { RBACApiClient::CrossAccountRequestWithRolesRolesInner.new }

  describe 'test an instance of CrossAccountRequestWithRolesRolesInner' do
    it 'should create an instance of CrossAccountRequestWithRolesRolesInner' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(RBACApiClient::CrossAccountRequestWithRolesRolesInner)
    end
  end

  describe 'test attribute "display_name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "description"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "permissions"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
