=begin
#Role Based Access Control

#The API for Role Based Access Control.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for RBACApiClient::Error403ErrorsInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe RBACApiClient::Error403ErrorsInner do
  let(:instance) { RBACApiClient::Error403ErrorsInner.new }

  describe 'test an instance of Error403ErrorsInner' do
    it 'should create an instance of Error403ErrorsInner' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(RBACApiClient::Error403ErrorsInner)
    end
  end

  describe 'test attribute "detail"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "source"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "status"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
