=begin
#Role Based Access Control

#The API for Role Based Access Control.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.1.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for RBACApiClient::PrincipalIn
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe RBACApiClient::PrincipalIn do
  let(:instance) { RBACApiClient::PrincipalIn.new }

  describe 'test an instance of PrincipalIn' do
    it 'should create an instance of PrincipalIn' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(RBACApiClient::PrincipalIn)
    end
  end

  describe 'test attribute "username"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
