=begin
#Role Based Access Control

#The API for Role Based Access Control.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for RBACApiClient::ResourceDefinitionFilter
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe RBACApiClient::ResourceDefinitionFilter do
  let(:instance) { RBACApiClient::ResourceDefinitionFilter.new }

  describe 'test an instance of ResourceDefinitionFilter' do
    it 'should create an instance of ResourceDefinitionFilter' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(RBACApiClient::ResourceDefinitionFilter)
    end
  end

  describe 'test attribute "key"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "operation"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["equal", "in"])
      # validator.allowable_values.each do |value|
      #   expect { instance.operation = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "value"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
