=begin
#Role Based Access Control

#The API for Role Based Access Control.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.2

=end

# Common files
require 'insights-rbac-api-client/api_client'
require 'insights-rbac-api-client/api_error'
require 'insights-rbac-api-client/version'
require 'insights-rbac-api-client/configuration'

# Models
require 'insights-rbac-api-client/models/access'
require 'insights-rbac-api-client/models/access_pagination'
require 'insights-rbac-api-client/models/access_pagination_all_of'
require 'insights-rbac-api-client/models/additional_group'
require 'insights-rbac-api-client/models/error'
require 'insights-rbac-api-client/models/error403'
require 'insights-rbac-api-client/models/group'
require 'insights-rbac-api-client/models/group_out'
require 'insights-rbac-api-client/models/group_pagination'
require 'insights-rbac-api-client/models/group_pagination_all_of'
require 'insights-rbac-api-client/models/group_principal_in'
require 'insights-rbac-api-client/models/group_role_in'
require 'insights-rbac-api-client/models/group_roles_pagination'
require 'insights-rbac-api-client/models/group_with_principals'
require 'insights-rbac-api-client/models/group_with_principals_all_of'
require 'insights-rbac-api-client/models/group_with_principals_and_roles'
require 'insights-rbac-api-client/models/group_with_principals_and_roles_all_of'
require 'insights-rbac-api-client/models/inline_response200'
require 'insights-rbac-api-client/models/list_pagination'
require 'insights-rbac-api-client/models/pagination_links'
require 'insights-rbac-api-client/models/pagination_meta'
require 'insights-rbac-api-client/models/policy'
require 'insights-rbac-api-client/models/policy_extended'
require 'insights-rbac-api-client/models/policy_extended_all_of'
require 'insights-rbac-api-client/models/policy_in'
require 'insights-rbac-api-client/models/policy_in_all_of'
require 'insights-rbac-api-client/models/policy_pagination'
require 'insights-rbac-api-client/models/policy_pagination_all_of'
require 'insights-rbac-api-client/models/principal'
require 'insights-rbac-api-client/models/principal_in'
require 'insights-rbac-api-client/models/principal_out'
require 'insights-rbac-api-client/models/principal_pagination'
require 'insights-rbac-api-client/models/principal_pagination_all_of'
require 'insights-rbac-api-client/models/resource_definition'
require 'insights-rbac-api-client/models/resource_definition_filter'
require 'insights-rbac-api-client/models/role'
require 'insights-rbac-api-client/models/role_in'
require 'insights-rbac-api-client/models/role_in_all_of'
require 'insights-rbac-api-client/models/role_out'
require 'insights-rbac-api-client/models/role_out_dynamic'
require 'insights-rbac-api-client/models/role_out_dynamic_all_of'
require 'insights-rbac-api-client/models/role_pagination'
require 'insights-rbac-api-client/models/role_pagination_dynamic'
require 'insights-rbac-api-client/models/role_pagination_dynamic_all_of'
require 'insights-rbac-api-client/models/role_with_access'
require 'insights-rbac-api-client/models/status'
require 'insights-rbac-api-client/models/timestamped'
require 'insights-rbac-api-client/models/uuid'

# APIs
require 'insights-rbac-api-client/api/access_api'
require 'insights-rbac-api-client/api/group_api'
require 'insights-rbac-api-client/api/policy_api'
require 'insights-rbac-api-client/api/principal_api'
require 'insights-rbac-api-client/api/role_api'
require 'insights-rbac-api-client/api/status_api'

module RBACApiClient
  class << self
    # Customize default settings for the SDK using block.
    #   RBACApiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
