=begin
#Role Based Access Control

#The API for Role Based Access Control.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.4.0

=end

# Common files
require 'insights-rbac-api-client/api_client'
require 'insights-rbac-api-client/api_error'
require 'insights-rbac-api-client/version'
require 'insights-rbac-api-client/configuration'

# Models
require 'insights-rbac-api-client/models/access'
require 'insights-rbac-api-client/models/access_pagination'
require 'insights-rbac-api-client/models/add_role_to_group200_response'
require 'insights-rbac-api-client/models/additional_group'
require 'insights-rbac-api-client/models/cross_account_request'
require 'insights-rbac-api-client/models/cross_account_request_by_account'
require 'insights-rbac-api-client/models/cross_account_request_by_user_id'
require 'insights-rbac-api-client/models/cross_account_request_detail'
require 'insights-rbac-api-client/models/cross_account_request_detail_by_account'
require 'insights-rbac-api-client/models/cross_account_request_detail_by_use_id'
require 'insights-rbac-api-client/models/cross_account_request_in'
require 'insights-rbac-api-client/models/cross_account_request_out'
require 'insights-rbac-api-client/models/cross_account_request_pagination'
require 'insights-rbac-api-client/models/cross_account_request_pagination_all_of_data'
require 'insights-rbac-api-client/models/cross_account_request_patch'
require 'insights-rbac-api-client/models/cross_account_request_update_in'
require 'insights-rbac-api-client/models/cross_account_request_with_roles'
require 'insights-rbac-api-client/models/cross_account_request_with_roles_roles_inner'
require 'insights-rbac-api-client/models/error'
require 'insights-rbac-api-client/models/error403'
require 'insights-rbac-api-client/models/error403_errors_inner'
require 'insights-rbac-api-client/models/error_errors_inner'
require 'insights-rbac-api-client/models/error_not_found'
require 'insights-rbac-api-client/models/error_not_found_errors_inner'
require 'insights-rbac-api-client/models/get_principals_from_group200_response'
require 'insights-rbac-api-client/models/group'
require 'insights-rbac-api-client/models/group_out'
require 'insights-rbac-api-client/models/group_pagination'
require 'insights-rbac-api-client/models/group_principal_in'
require 'insights-rbac-api-client/models/group_principal_in_principals_inner'
require 'insights-rbac-api-client/models/group_role_in'
require 'insights-rbac-api-client/models/group_roles_pagination'
require 'insights-rbac-api-client/models/group_with_principals'
require 'insights-rbac-api-client/models/group_with_principals_and_roles'
require 'insights-rbac-api-client/models/list_pagination'
require 'insights-rbac-api-client/models/list_principals200_response'
require 'insights-rbac-api-client/models/pagination_links'
require 'insights-rbac-api-client/models/pagination_meta'
require 'insights-rbac-api-client/models/permission'
require 'insights-rbac-api-client/models/permission_options_pagination'
require 'insights-rbac-api-client/models/permission_pagination'
require 'insights-rbac-api-client/models/policy'
require 'insights-rbac-api-client/models/policy_extended'
require 'insights-rbac-api-client/models/policy_in'
require 'insights-rbac-api-client/models/policy_pagination'
require 'insights-rbac-api-client/models/principal'
require 'insights-rbac-api-client/models/principal_external_source_id'
require 'insights-rbac-api-client/models/principal_in'
require 'insights-rbac-api-client/models/principal_minimal'
require 'insights-rbac-api-client/models/principal_out'
require 'insights-rbac-api-client/models/principal_pagination'
require 'insights-rbac-api-client/models/principal_pagination_all_of_data'
require 'insights-rbac-api-client/models/resource_definition'
require 'insights-rbac-api-client/models/resource_definition_filter'
require 'insights-rbac-api-client/models/resource_definition_filter_value'
require 'insights-rbac-api-client/models/resource_definition_filter_value_one_of_inner'
require 'insights-rbac-api-client/models/role'
require 'insights-rbac-api-client/models/role_in'
require 'insights-rbac-api-client/models/role_out'
require 'insights-rbac-api-client/models/role_out_dynamic'
require 'insights-rbac-api-client/models/role_pagination'
require 'insights-rbac-api-client/models/role_pagination_dynamic'
require 'insights-rbac-api-client/models/role_patch'
require 'insights-rbac-api-client/models/role_with_access'
require 'insights-rbac-api-client/models/service_account'
require 'insights-rbac-api-client/models/service_account_in'
require 'insights-rbac-api-client/models/service_account_in_group_response'
require 'insights-rbac-api-client/models/service_account_pagination'
require 'insights-rbac-api-client/models/status'
require 'insights-rbac-api-client/models/timestamped'
require 'insights-rbac-api-client/models/uuid'

# APIs
require 'insights-rbac-api-client/api/access_api'
require 'insights-rbac-api-client/api/cross_account_request_api'
require 'insights-rbac-api-client/api/group_api'
require 'insights-rbac-api-client/api/permission_api'
require 'insights-rbac-api-client/api/policy_api'
require 'insights-rbac-api-client/api/principal_api'
require 'insights-rbac-api-client/api/role_api'
require 'insights-rbac-api-client/api/status_api'

module RBACApiClient
  class << self
    # Customize default settings for the SDK using block.
    #   RBACApiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
